const MOVIE_BASE_URL = "https://api.nomoreparties.co/beatfilm-movies";
const IMAGE_BASE_URL = "https://api.nomoreparties.co";
const BASE_URL = "https://api.maxmovies.nomoredomains.icu";
const SHORT_MOVIE_DURATION = 40;
const DISPLAYED_NUMBER_OF_MOVIES_THREE_IN_ROW = 12;
const DISPLAYED_NUMBER_OF_MOVIES_TWO_IN_ROW = 8;
const DISPLAYED_NUMBER_OF_MOVIES_ONE_IN_ROW = 5;
const LOAD_MORE_MOVIES_DESKTOP = 3;
const LOAD_MORE_MOVIES_MOBILE = 2;
// const BASE_URL = "http://localhost:3000";
export {
  MOVIE_BASE_URL,
  IMAGE_BASE_URL,
  BASE_URL,
  SHORT_MOVIE_DURATION,
  DISPLAYED_NUMBER_OF_MOVIES_THREE_IN_ROW,
  DISPLAYED_NUMBER_OF_MOVIES_TWO_IN_ROW,
  DISPLAYED_NUMBER_OF_MOVIES_ONE_IN_ROW,
  LOAD_MORE_MOVIES_DESKTOP,
  LOAD_MORE_MOVIES_MOBILE,
};
